trigger:
  branches:
    exclude:
      - '*'

 

pr:
  branches:
    exclude:
      - '*'

 

pool:
  name : 'azurevmtest'

 

variables:
  azureSubscription: 'Free Trial'
  azureFunctionAppName: 'FnnAppTest'
  gitHubRepository: 'https://github.com/dhananjay192/hello.git'
  gitHubBranch: 'main'

 

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: '$(azureSubscription)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Install Azure Functions Core Tools
      curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
      sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
      AZ_REPO=$(lsb_release -cs)
      echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
      sudo apt-get update
      sudo apt-get install azure-cli

 

      # Log in to Azure
      az login --service-principal --username "$(servicePrincipalId)" --password "$(servicePrincipalKey)" --tenant "$(tenantId)"

 

      # Clone the GitHub repository
      git clone $(gitHubRepository)

 

      # Deploy to Azure Functions
      cd $(GitHub Repository Name)
      az functionapp deployment source config-local-git --name $(azureFunctionAppName) --resource-group $(resourceGroupName)
      az functionapp deployment source sync --name $(azureFunctionAppName) --resource-group $(resourceGroupName)